pumps:
  esp:
    name: "Electric Submersible Pump"
    expected_life: 60  # months
    replacement_cost: 50000
    maintenance_interval: 3  # months
    failure_modes:
      - name: "Motor Failure"
        probability: 0.15
        cost_multiplier: 1.2
      - name: "Pump Wear"
        probability: 0.25
        cost_multiplier: 0.8
      - name: "Cable Issues"
        probability: 0.10
        cost_multiplier: 0.5
    
  rod_pump:
    name: "Rod Pump"
    expected_life: 84
    replacement_cost: 35000
    maintenance_interval: 6
    failure_modes:
      - name: "Rod Break"
        probability: 0.20
        cost_multiplier: 0.7
      - name: "Tubing Wear"
        probability: 0.15
        cost_multiplier: 0.9

separators:
  three_phase:
    name: "Three Phase Separator"
    expected_life: 120
    replacement_cost: 75000
    maintenance_interval: 12
    operating_parameters:
      max_pressure: 1500
      max_temperature: 200
      max_water_cut: 0.95

meters:
  production:
    name: "Production Meter"
    expected_life: 96
    replacement_cost: 15000
    calibration_interval: 6
    accuracy: 0.02

monitoring:
  parameters:
    - name: "Pressure"
      units: "psi"
      normal_range: [100, 3000]
      critical_range: [50, 3500]
    - name: "Temperature"
      units: "fahrenheit"
      normal_range: [80, 180]
      critical_range: [60, 200]
    - name: "Vibration"
      units: "in/s"
      normal_range: [0, 0.5]
      critical_range: [0, 1.0]