pump_system:
  name: "Electric Submersible Pump"
  expected_life: 60  # months
  replacement_cost: 50000
  failure_impact: 0.8
  maintenance_schedule: 3
  components:
    motor:
      life_hours: 40000
      cost: 15000
      critical: true
    pump:
      life_hours: 30000
      cost: 25000
      critical: true
    cable:
      life_hours: 50000
      cost: 8000
      critical: false
  maintenance_tasks:
    - task: "Oil Change"
      frequency: 3  # months
      cost: 500
    - task: "Bearing Inspection"
      frequency: 6
      cost: 1200
    - task: "Motor Testing"
      frequency: 12
      cost: 2000

wellhead:
  name: "Wellhead Assembly"
  expected_life: 120
  replacement_cost: 75000
  failure_impact: 1.0
  maintenance_schedule: 6
  components:
    casing_head:
      life_hours: 87600
      cost: 30000
      critical: true
    tubing_head:
      life_hours: 87600
      cost: 25000
      critical: true
    valves:
      life_hours: 43800
      cost: 15000
      critical: true
  maintenance_tasks:
    - task: "Pressure Testing"
      frequency: 6
      cost: 1500
    - task: "Valve Service"
      frequency: 12
      cost: 3000
    - task: "Seal Replacement"
      frequency: 24
      cost: 5000

separator:
  name: "Three-Phase Separator"
  expected_life: 84
  replacement_cost: 40000
  failure_impact: 0.6
  maintenance_schedule: 4
  components:
    vessel:
      life_hours: 70000
      cost: 25000
      critical: true
    controls:
      life_hours: 35000
      cost: 10000
      critical: false
    instruments:
      life_hours: 30000
      cost: 5000
      critical: false
  maintenance_tasks:
    - task: "Vessel Inspection"
      frequency: 12
      cost: 2000
    - task: "Control Calibration"
      frequency: 6
      cost: 1000
    - task: "Level Control Service"
      frequency: 4
      cost: 800

storage_tanks:
  name: "Storage Tank System"
  expected_life: 180
  replacement_cost: 100000
  failure_impact: 0.7
  maintenance_schedule: 12
  components:
    tanks:
      life_hours: 131400
      cost: 70000
      critical: true
    gauges:
      life_hours: 43800
      cost: 5000
      critical: false
    valves:
      life_hours: 43800
      cost: 15000
      critical: true
  maintenance_tasks:
    - task: "Tank Inspection"
      frequency: 12
      cost: 3000
    - task: "Coating Inspection"
      frequency: 24
      cost: 5000
    - task: "Calibration"
      frequency: 6
      cost: 1000
