
permits:
  operating:
    name: "Operating Permit"
    renewal_interval: 12  # months
    cost: 5000
    requirements:
      - "Production Reports"
      - "Equipment Inspections"
      - "Safety Compliance"
    
  disposal:
    name: "Water Disposal Permit"
    renewal_interval: 6
    cost: 3000
    requirements:
      - "Water Analysis"
      - "Disposal Well Tests"
      - "Volume Reports"

inspections:
  types:
    mechanical:
      frequency: 3  # months
      duration: 4  # hours
      cost: 1500
    
    environmental:
      frequency: 6
      duration: 8
      cost: 2500
    
    safety:
      frequency: 1
      duration: 2
      cost: 800

reporting:
  production:
    frequency: "monthly"
    deadline_day: 15
    format: "electronic"
    required_data:
      - "Oil Production"
      - "Water Production"
      - "Gas Production"
      - "Pressure Readings"
  
  environmental:
    frequency: "quarterly"
    deadline_day: 30
    format: "electronic"
    required_data:
      - "Water Analysis"
      - "Emissions Data"
      - "Spill Reports"

compliance:
  environmental:
    water_disposal:
      max_pressure: 2000  # psi
      max_volume: 10000  # bbl/day
      testing_frequency: "monthly"
    
    emissions:
      monitoring: "continuous"
      reporting: "quarterly"
      thresholds:
        methane: 100  # ppm
        voc: 50  # ppm
    
    spill_prevention:
      plan_update_frequency: 60  # months
      training_frequency: 12  # months
      inspection_frequency: 1  # month

  safety:
    training:
      initial_hours: 40
      refresher_hours: 8
      frequency: 12  # months
    
    equipment:
      inspection_frequency: 1  # month
      certification_frequency: 12  # months
    
    emergency_response:
      plan_update_frequency: 12  # months
      drill_frequency: 6  # months