logging:
  level: INFO
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  file: logs/well_analysis.log

data:
  input_dir: data/raw
  output_dir: data/processed
  backup_dir: data/backup

monte_carlo:
  n_simulations: 1000
  seed: 42
  confidence_level: 0.95

optimization:
  max_iterations: 1000
  tolerance: 1e-6
  method: 'SLSQP'

visualization:
  theme: 'plotly_white'
  color_palette: 'Blues'
  plot_width: 800
  plot_height: 600
